name: yor-tagging
on:
  # Trigger the workflow on pull request,
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *' # Every day at 8 AM
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
